export default {
    'LOAD_DATA': 'LOAD_DATA',
    'SORT_DATA': 'SORT_DATA',
    'UPDATE_PAGE_DATA': 'UPDATE_PAGE_DATA',
    'FLIP_PAGE': 'FLIP_PAGE',
    'CHANGE_ROWS_PER_PAGE': 'CHANGE_ROWS_PER_PAGE',
    'CHANGE_ORDER': 'CHANGE_ORDER',
    'ADD_SELECTED': 'ADD_SELECTED',
    'REMOVE_SELECTED': 'REMOVE_SELECTED'
}