export default {
    'ASSIGN_CLAIM_REQUEST': 'ASSIGN_CLAIM_REQUEST',
    'ASSIGN_CLAIM_SUCCESS': 'ASSIGN_CLAIM_SUCCESS',
    'ASSIGN_CLAIM_FAILURE': 'ASSIGN_CLAIM_FAILURE',

    'ACCEPT_CLAIM_REQUEST': 'ACCEPT_CLAIM_REQUEST',
    'ACCEPT_CLAIM_SUCCESS': 'ACCEPT_CLAIM_SUCCESS',
    'ACCEPT_CLAIM_FAILURE': 'ACCEPT_CLAIM_FAILURE',

    'REJECT_CLAIM_REQUEST': 'REJECT_CLAIM_REQUEST',
    'REJECT_CLAIM_SUCCESS': 'REJECT_CLAIM_SUCCESS',
    'REJECT_CLAIM_FAILURE': 'REJECT_CLAIM_FAILURE',

    'UPDATE_CLAIMS': 'UPDATE_CLAIMS'
}