export default {
    'FILE_CLAIMS_REQUEST': 'FILE_CLAIMS_REQUEST',
    'FILE_CLAIMS_SUCCESS': 'FILE_CLAIMS_SUCCESS',
    'FILE_CLAIMS_FAILURE': 'FILE_CLAIMS_FAILURE',

    'FETCH_CLAIMS_REQUEST': 'FETCH_CLAIMS_REQUEST',
    'FETCH_CLAIMS_SUCCESS': 'FETCH_CLAIMS_SUCCESS',
    'FETCH_CLAIMS_FAILURE': 'FETCH_CLAIMS_FAILURE'
}