export default {
    'FETCH_INSURANCES_REQUEST': 'FETCH_INSURANCES_REQUEST',
    'FETCH_INSURANCES_SUCCESS': 'FETCH_INSURANCES_SUCCESS',
    'FETCH_INSURANCES_FAILURE': 'FETCH_INSURANCES_FAILURE',

    'CREATE_INSURANCE_REQUEST': 'CREATE_INSURANCE_REQUEST',
    'CREATE_INSRUANCE_SUCCESS': 'CREATE_INSRUANCE_SUCCESS',
    'CREATE_INSRUANCE_FAILURE': 'CREATE_INSRUANCE_FAILURE'
}