export default {
    'FETCH_PROFILE_REQUEST': 'FETCH_PROFILE_REQUEST',
    'FETCH_SELF_PROFILE_SUCCESS': 'FETCH_SELF_PROFILE_SUCCESS',
    'FETCH_SELF_PROFILE_FAILURE': 'FETCH_SELF_PROFILE_FAILURE',
    'FETCH_PROFILES_SUCCESS': 'FETCH_PROFILES_SUCCESS',
    'FETCH_PROFILES_FAILURE': 'FETCH_PROFILES_FAILURE',

    'CREATE_PROFILE_REQUEST': 'CREATE_PROFILE_REQUEST',
    'CREATE_PROFILE_SUCCESS': 'CREATE_PROFILE_SUCCESS',
    'CREATE_PROFILE_FAILURE': 'CREATE_PROFILE_FAILURE',

    'UPDATE_PROFILE_REQUEST': 'UPDATE_PROFILE_REQUEST',
    'UPDATE_PROFILE_SUCCESS': 'UPDATE_PROFILE_SUCCESS',
    'UPDATE_PROFILE_FAILURE': 'UPDATE_PROFILE_FAILURE'
}